### ISSUE TITLE
Error when trying to set/detect language (English)

### ISSUE THREAD

**Issue by kellykendro** [unDocUMeantIt/koRpus.lang.en#2]
Due to these issues, I can't move forward with the analysis. My original code, which loaded koRpus, had this line:

`hdd <- HDD(text)`

which resulted in this error message:

_Error: No language specified!_

I then loaded koRpus.lang.en and attempted the same line which resulted in this error message:

_Error in HDD(text) : could not find function "HDD"_

The same error regarding HDD also occurred when I tried the following lines:

`  koRpus::hdd <- HDD(text)`

`  koRpus.lang.en::hdd <- HDD(text)`

I was also unable to set the language manually using:

`setCorpusLanguage("en")`

`hdd <- HDD(text, lang="en")`

**Comment by unDocUMeantIt** [comment]
i can't replicate the issue. could you please post a complete reproduceable portion of code and not just the line that fails with an error?

some hints:

* loading `koRpus.lang.en` alone does not tell `HDD()` or any other functions which language to use, as you can load multiple `koRpus.lang.*` packages at once. please refer to the documentation, esp. `?set.kRp.env()`
* what exactly is `text` in your example? in case it's the result of either `koRpus::treetag()` or `koRpus::tokenize()` (which it should be), it should already contain a language definition
* there is no `hdd` object in `koRpus.lang.en`, which only contains language specific information for `koRpus` but no functions for analysis
* `koRpus::hdd <- HDD(text)` is trying to assign a value to something inside the `koRpus` package environment, which looks completely wrong. perhaps you meant to call `koRpus::HDD(...)`?
* there is no function called `setCorpusLanguage()` in `koRpus`

**Comment by kellykendro** [comment]
Thank you! I found the issue; it was with TreeTagger.
